name: Validate answers

on:
  workflow_dispatch:
  repository_dispatch:
    types: [answer_submission]

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - env:
          ENCRYPTED_CLIENT_PAYLOAD: ${{ github.event.client_payload.encryptedBody }}
          ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD }}
        run: node scoreboard/answer_validator/index.js