name: Validate answers

on:
  workflow_dispatch:
  repository_dispatch:
    types: [answer_submission]

jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - run: go version
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
      - env:
          JSON_DOC: ${{ toJSON(github.event.client_payload) }}
        run: |
          printf '%s\n' "$JSON_DOC" > foo.json
          cat foo.json
      
