name: Validate answers

on:
  workflow_dispatch:
  repository_dispatch:
    types: [answer_submission]

jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - run: printenv
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - env:
          CLIENT_PAYLOAD: ${{ toJSON(github.event.client_payload) }}
        run: node answer_validator/index.js
