name: Validate answers

on:
  workflow_dispatch:
  repository_dispatch:
    types: [answer_submission]

jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - env:
          CLIENT_PAYLOAD: ${{ toJSON(github.event.client_payload) }}
        run: |
          node answer_validator/index.js
