name: Process results

on:
  workflow_run:
    workflows: ["Validate answers"]
    types: [completed]


jobs:
  process:
    runs-on: ubuntu-22.04
    steps:
      - if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: echo $test
        env:
          test: ${{ toJSON(github.event.workflow_run.conclusion) }}